name: Dead Penguins
description: Dead Penguins Blog 
baseurl: ""
links:
    About:
        url: #
    Wiki:
        url: https://github.com/deadpenguins/deadpenguins.github.io/wiki
    GitHub:
        url: https://github.com/deadpenguins/deadpenguins.github.io 
    Twitter:
        url: #
    Youtube:
        url: # 
authors:
    drew:
        name: Drew
        email: uo.is.ou@gmail.com
    hex:
        name: HexDSL
        email: HexDSL@Gmail.com 
#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/
